from typing import Any

from .models import BaseLLMClient


class PlaceholderLLMClient(BaseLLMClient):
    """
    Placeholder AI client.

    This does NOT call any real model.
    It only returns a generic template response so that:

      - The library has a fully working end-to-end flow.
      - Users can fork the project and replace this implementation
        with a real provider (OpenAI, local model, etc).

    See the README for instructions on creating a real client.
    """

    def generate(self, prompt: str, **kwargs: Any) -> str:
        # In a real client, you would send `prompt` to an LLM here.
        # This is just a stub that demonstrates the shape of the output.
        return (
            "This is a placeholder AI response.\n\n"
            "In a real setup, this text would be generated by a language model.\n"
            "The model would use the prompt (which includes the file structure)\n"
            "to produce a screen-reader-friendly explanation and navigation cues\n"
            "for a blind or low-vision developer.\n\n"
            "To connect a real model, implement a subclass of BaseLLMClient\n"
            "and override the generate() method to call your chosen provider."
        )